apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: zhollb/repo:react
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: reactapp
spec:
  type: LoadBalancer
  selector:
    app: reactapp
  ports:
  - port: 80
    targetPort: 3000

